$(document).ready(function(){
          $(".owl-crousel").owlCarousel({
                    items:3,
                    loop:true,
                    navigation:false,
                    dots:false,
                    autoplay:true,
                    autoplaySpeed:1000,
                    smartSpeed:2000,
                    autoplayHoverPause:true,
          });
          console.log("true")
});